### ISSUE TITLE
大佬能否考虑针对 telegram 添加代理选项

### ISSUE THREAD

**Issue by zhongwangninja** [JunzhouLiu/BILIBILI-HELPER-PRE#10]
用的国内小鸡，但电报做结果推送，目前没法做到。

大佬能否考虑增加对 telegram 的代理支持，方案可以类似是添加诸如如下的三个参数：
TELEGRAMBOTPROXY：true 表示使用代理，默认 false 不走代理；
TELEGRAMBOTPROXYHOST：代理 ip 地址
TELEGRAMBOTPROXYPORT：代理端口

支持 http 或者 sock5 这类常用的代理类型任意一种，就可以很方便的用国内小鸡推送结果到电报。

**Comment by JunzhouLiu** [comment]
在做了，新版本会好用很多。
