### ISSUE TITLE
大佬有没有考虑添加个企业微信应用推送了

### ISSUE THREAD

**Issue by graytoowolf** [JunzhouLiu/BILIBILI-HELPER-PRE#11]
大佬有没有考虑添加个企业微信应用推送了。现在免费版Server酱 不好用了。难受

**Comment by JunzhouLiu** [comment]
企业微信推送是有相关实现的，只需要讲server酱的key替换为企业微信的key就好了。

**Comment by graytoowolf** [comment]
> 企业微信推送是有相关实现的，只需要将server酱的key替换为企业微信的key就好了。

你现在的企业微信推送是群机器人推送吧。我的意思是企业微信第三方应用推送，不是群机器人推送，群机器人推送微信接受不到消息的。
https://work.weixin.qq.com/api/doc/90001/90143/90372

**Comment by JunzhouLiu** [comment]
> > 企业微信推送是有相关实现的，只需要将server酱的key替换为企业微信的key就好了。
> 
> 你现在的企业微信推送是群机器人推送吧。我的意思是企业微信第三方应用推送，不是群机器人推送，群机器人推送微信接受不到消息的。
> https://work.weixin.qq.com/api/doc/90001/90143/90372

我说的就是企业微信的原生实现。只需要酱server酱的key，换成企业微信的key即可，工具会自动识别key的类型。

**Comment by JunzhouLiu** [comment]
确认下是否是这个api接口 `https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=`

**Comment by graytoowolf** [comment]
> 确认下是否是这个api接口 `https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=`

这个接口就是企业微信群机器人接口。
我说的是这个文档的接口：https://work.weixin.qq.com/api/doc/90001/90143/90372#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89

**Comment by JunzhouLiu** [comment]
> > 确认下是否是这个api接口 `https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=`
> 
> 这个接口就是企业微信群机器人接口。
> 我说的是这个文档的接口：https://work.weixin.qq.com/api/doc/90001/90143/90372#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89

ok 明白了，这个改起来还有点麻烦，需要指定agentid和推送类型，推送这块后面调整一下。会通过外部配置读取推送相关的配置。原先的推送参数读取放到现在弊大于利了。

**Comment by graytoowolf** [comment]
> > > 确认下是否是这个api接口 `https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=`
> > 
> > 
> > 这个就是企业微信群机器人接口。
> > 我说的是文档这个接口的接口：[https://work.weixin.qq.com/api/doc/90001/90143/90372#%E5%9B%BE%E6%96 %87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89](https://work.weixin.qq.com/api/doc/90001/90143/90372#%E5%9B%BE%E6%96%87%E6%B6%88%E6%81%AF%EF%BC%88mpnews%EF%BC%89)
> 
> 好的明白了，这个改起来还有，需要指定agentid和点配置类型，这会通过外部配置读取相关的信息。

可以参考jd脚本：https://note.youdao.com/ynoteshare/index.html?id=351e08a72378206f9dd64d2281e9b83b&type=note&_time=1631328844683  这样设置一个key就很方便

**Comment by itning** [comment]
@graytoowolf 推送到企业微信应用需要调用接口凭证ACCESS_TOKEN，这个是有时效的 
让用户传进来吗

**Comment by itning** [comment]
哦哦 先获取TOKEN 没事了

**Comment by itning** [comment]
Support Since #34
