### ISSUE TITLE
是否能在 config.json 中自定义 SERVER_PUSH_TELEGRAM 

### ISSUE THREAD

**Issue by InPRTx** [JunzhouLiu/BILIBILI-HELPER-PRE#12]
有能力的，可以自建搭建一个 telegram-api 服务器（降低到dc5的延迟）
https://github.com/tdlib/telegram-bot-api

看上去这个项目把这个api地址写死了
https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/blob/01d752c5f346c6476f253b9636c578d45a46a418/src/main/java/top/misec/api/ApiList.java#L15

**Comment by JunzhouLiu** [comment]
###后续考虑支持该功能，这个功能做起来并不是很麻烦。

**Comment by itning** [comment]
Support In 
https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/commit/2752e15b10dba680bdab037a5c11d0a9f0459f53
