### ISSUE TITLE
希望能配置是否自动银瓜子兑换硬币

### ISSUE THREAD

**Issue by jkluio78** [JunzhouLiu/BILIBILI-HELPER-PRE#13]

**Comment by jkluio78** [comment]
我想的是能否根据配置文件填的值，来决定是否在dailyTasks添加Silver2coin()任务呢？
如果填true，则 dailyTasks.add(new Silver2coin());
不填则不加

**Comment by JunzhouLiu** [comment]
> 决定是否在dailyTask

2.0.0会考虑此开关

**Comment by jkluio78** [comment]
我能写一个发个PR吗
