### ISSUE TITLE
docker版本推送失效

### ISSUE THREAD

**Issue by dhbowen1** [JunzhouLiu/BILIBILI-HELPER-PRE#15]
2021-09-12 11:33:40 INFO  : 未配置正确的ftKey和chatId,本次执行将不推送日志
用的SuperNG6/docker-bilibili-helper配置的，以前老版本都正常推送，昨天升级新版后就提示这个了，配置都没有变
神奇了
他用的推送变量是
SERVERPUSHKEY | 通过server酱推送执行结果到微信(可选项)
这个明明也设置的对啊

**Comment by dhbowen1** [comment]
直接容器内用java -jar /home/BILIBILI-HELPER.jar DEDEUSERID SESSDATA BILI_JCT SCKEY运行也提示：未配置正确的ftKey和chatId,本次执行将不推送日志

**Comment by JunzhouLiu** [comment]
> 直接容器内用java -jar /home/BILIBILI-HELPER.jar DEDEUSERID SESSDATA BILI_JCT SCKEY运行也提示：未配置正确的ftKey和chatId,本次执行将不推送日志

 最近在调整推送，v2.0.0-pre很快就会放出来。

**Comment by JunzhouLiu** [comment]
测试了下，没问题的呀 
![image](https://user-images.githubusercontent.com/17582066/132979025-6f1742b9-396c-4a26-bd49-ba727870b3bf.png)

**Comment by dhbowen1** [comment]
我知道为什么不行了你测试的是server turbo版本
原先的老版本其实还能使用，一直也可以推送，腾讯还没有关闭，作者也说支持到关闭为止。老版本不需要点开。老版本推送会有这个提示

**Comment by JunzhouLiu** [comment]
> 我知道为什么不行了你测试的是server turbo版本
> 原先的老版本其实还能使用，一直也可以推送，腾讯还没有关闭，作者也说支持到关闭为止。老版本不限量。老版本推送会失败，我同样甜糖每天都在推送到这个普通版上。跟以前一样正常使用。
> 还有一个问题，企业微信群推送设置上也会提示失败，还没有适配吗？

老版本我已经下掉了。。。

**Comment by dhbowen1** [comment]
能加上吗大佬，老版本是真的好用，只要还有STU码一直可以推送

**Comment by dhbowen1** [comment]
腾讯好像无限延期了，短期不会关闭。方糖服务号也说会一直支持到腾讯关闭。

**Comment by JunzhouLiu** [comment]
> 腾讯好像无限延期了，短期不会关闭。方糖服务号也说会一直支持到腾讯关闭。

> 能加上吗大佬，老版本是真的好用，只要还有STU码一直可以推送

@itning 可否在main分支恢复对老版本server酱的支持？ 以及在v2.0.0-pre分之继续提供对老版server酱的支持？

原serverchanpush的实现类：
https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/blob/b56d350423d44d495c15aef00d7dc4324336919a/src/main/java/top/misec/push/impl/ServerChanPush.java

**Comment by dhbowen1** [comment]
多谢
