### ISSUE TITLE
赛事预测

### ISSUE THREAD

**Issue by wym3253** [JunzhouLiu/BILIBILI-HELPER-PRE#16]
[请问一下赛事预测是指的这个界面吗](https://www.bilibili.com/v/game/match/competition)
在配置文件开启赛事预测后，11日和12日并没有执行赛事预测。
还有每次推送到TG时，
![图片](https://user-images.githubusercontent.com/14027314/132981996-3a51279a-e273-4e09-ba62-137442c06112.png)
这个图片显示能不能关闭？

**Comment by JunzhouLiu** [comment]
1.  赛事预测需要手动预测一次，后续程序才能成功预测，没有执行预测的话，可能当天没有赛事

2. 这个图片是tg对链接的自动识别产生的卡片。并非是我加入的卡片。
