### ISSUE TITLE
Server酱推送，提示失败，实际推送成功。

### ISSUE THREAD

**Issue by dhbowen1** [JunzhouLiu/BILIBILI-HELPER-PRE#17]
![image](https://user-images.githubusercontent.com/76920125/133044707-b06272ce-c914-41ff-9f38-7886964d11dc.png)
刚更恢复的Server酱推送，提示失败，实际是成功的。就是这么判断的？还是？

**Comment by JunzhouLiu** [comment]
先凑合着用吧，后面马上2.0就出来了。
