### ISSUE TITLE
（云函数）关于企业微信机器人推送问题

### ISSUE THREAD

**Issue by davget** [JunzhouLiu/BILIBILI-HELPER-PRE#19]
我按照https://note.youdao.com/ynoteshare/index.html?id=351e08a72378206f9dd64d2281e9b83b&type=note&_time=1631328844683 设置了企业微信key，但是日志里显示：“未配置正确的ftKey和chatId,本次执行将不推送日志”
请问大佬这是哪里出了问题，拜谢

**Comment by JunzhouLiu** [comment]
目前只支持企业微信群内通知。
