### ISSUE TITLE
企业微信应用通知分割的建议

### ISSUE THREAD

**Issue by zhongwangninja** [JunzhouLiu/BILIBILI-HELPER-PRE#38]
看到企业微信应用通知已经开始支持图文模式，所以建议：
1. 如果使用文字模式就进行 1000 字的分割，发送多条通知；
2. 如果使用图文模式，就不用分割处理，图文模式应该没有字数限制，点击图片进入网页后能够完整展示通知内容

**Comment by itning** [comment]
#36 已支持
