### ISSUE TITLE
可以支持风纪委员投票的功能吗

### ISSUE THREAD

**Issue by Re1uy** [JunzhouLiu/BILIBILI-HELPER-PRE#43]

**Comment by graytoowolf** [comment]
基于以下几点考虑，风纪委员投票目前暂时不会合并到主分支。

本工具的初衷就是简化家获取每日经验的步骤，辅助大家更好的使用b站，领取自己可以领取的福利，并不想发展成一个破坏社区公平（抽奖，天选，风纪委员自动化）的工具，这一点很早就在readme中说明了。

虽然目前已经有很多开源的风纪委员的投票工具了，从开发者角度，我认为风纪委员的初衷就是维护社区发言，自治的工具，大规模的随机投票会导致误伤正常用户，破坏社区的自治能力。

**Comment by C-isco** [comment]
> 基于以下几点考虑，风纪委员投票目前暂时不会合并到主分支。
> 
> 本工具的初衷就是简化家获取每日经验的步骤，辅助大家更好的使用b站，领取自己可以领取的福利，并不想发展成一个破坏社区公平（抽奖，天选，风纪委员自动化）的工具，这一点很早就在readme中说明了。
> 
> 虽然目前已经有很多开源的风纪委员的投票工具了，从开发者角度，我认为风纪委员的初衷就是维护社区发言，自治的工具，大规模的随机投票会导致误伤正常用户，破坏社区的自治能力。

**Comment by C-isco** [comment]
了解了，谢谢大佬的回复

**Comment by JunzhouLiu** [comment]
暂时没有风纪委员投票相关的功能和计划。
