### ISSUE TITLE
能出一个青龙的教程不？

### ISSUE THREAD

**Issue by 17huiwei** [JunzhouLiu/BILIBILI-HELPER-PRE#51]
比较方便管理和控制哈。我linux的crontab老是失败。

**Comment by graytoowolf** [comment]
用云函数不香吗

**Comment by graytoowolf** [comment]
![QQ截图20210929114845](https://user-images.githubusercontent.com/57069542/135200348-126f21ca-f4d6-4bc8-a495-1d91a714008d.jpg)
**apk add openjdk8**
首先添加这个任务安装java,**这个任务只用一次**

然后上传**BILIBILI-HELPER-v2.0.9.jar** **config.json** 这两个文件到 **/ql/scripts/**这个目录。
再添加下面这个任务就可以了
**java -jar /ql/scripts/BILIBILI-HELPER-v2.0.9.jar /ql/scripts/config.json**
![QQ截图20210929115043](https://user-images.githubusercontent.com/57069542/135200357-7f0b79b4-4222-4607-ba9b-7d07ee8f621c.jpg)

**Comment by 17huiwei** [comment]
十分感谢！！太惊喜了。另外有个小问题，我有另外一个程序也使用了/ql/scripts/config.json，请问有办法处理么？多谢老大。

**Comment by graytoowolf** [comment]
> 十分感谢！！太惊喜了。另外有个小问题，我有另外一个程序也使用了/ql/scripts/config.json，请问有办法处理么？多谢老大。

在scripts新建个文件夹放B站的东西不就可以了

**Comment by JunzhouLiu** [comment]
> 十分感谢！！太惊喜了。另外有个小问题，我有另外一个程序也使用了/ql/scripts/config.json，请问有办法处理么？多谢老大。

把bili的config.json 改个名， bili-config.json 执行命令使用这个新名字。
