### ISSUE TITLE
云函数，关于企业微信应用推送问题

### ISSUE THREAD

**Issue by davget** [JunzhouLiu/BILIBILI-HELPER-PRE#54]
配置完后，无法进行正常推送，日志如下
![1~ Q 97K2W$7ZI9E1`V`1AU](https://user-images.githubusercontent.com/83133164/135263189-0c78d44b-730a-4d4f-be3a-acdaa15659c8.png)

**Comment by davget** [comment]
![KTE~487T$YU6Q56W L~AG45](https://user-images.githubusercontent.com/83133164/135267122-d2f77e71-e55d-4f77-9fc2-e49d189c4e4e.png)

**Comment by itning** [comment]
https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/releases/tag/v2.0.11
使用最新版再试下
