### ISSUE TITLE
青龙中pushplus+的推送失败了

### ISSUE THREAD

**Issue by 17huiwei** [JunzhouLiu/BILIBILI-HELPER-PRE#59]
TG的没问题，但是pushplus不知道为啥收不到了？

另外，教程最后的bili.sh的运行路径写错了，应该是task /ql/scripts/bili.sh

最后，十分感谢老大的迅速响应！

**Comment by graytoowolf** [comment]
兄弟你应该把日志放上来的。不然作者怎么知道哪里错了

**Comment by popsee** [comment]
大佬，一天更新两版本，简直不要太勤奋，还好config没变，要不还得低头撅腚改参数！
Best wishes! Happy National Day
