### ISSUE TITLE
通过钉钉通知失败

### ISSUE THREAD

**Issue by JianHaoZhangHB** [JunzhouLiu/BILIBILI-HELPER-PRE#6]
现确定Web Hook没有问题，Gitee仓库能够成功推送消息，仓库用的V1.0.3。
下面是云函数的日志，前面的都没有问题，就是推送钉钉失败
![截屏2021-08-13 上午11 39 50](https://user-images.githubusercontent.com/22268371/129301857-567dba87-aec3-4858-bef6-7bb92f7024b3.png)

**Comment by nssiwi** [comment]
钉钉是不是没有填密钥的地方

**Comment by JunzhouLiu** [comment]
最近会调整推送相关的代码。

**Comment by ours1505** [comment]
现在还没有修好吗

**Comment by JunzhouLiu** [comment]
> 现在还没有修好吗

钉钉群是没问题的呀。

**Comment by itning** [comment]
> 钉钉是不是没有填密钥的地方

Now Support ,See #28
