### ISSUE TITLE
[已解决]运行后的界面中文是乱码,请问怎么解决?

### ISSUE THREAD

**Issue by Jack77793** [JunzhouLiu/BILIBILI-HELPER-PRE#62]
rt,见图片,请问怎么解决?谢谢.
![QQ图片20211001091516](https://user-images.githubusercontent.com/77228575/135550885-90b7caa2-b7e1-45a4-b4f0-68aba8ff5af2.png)

**Comment by itning** [comment]
请在终端输入
chcp 65001
再运行jar包

**Comment by Jack77793** [comment]
好的,已收到,已解决,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JunzhouLiu/BILIBILI-HELPER-PRE"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月1日(星期五) 上午9:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [JunzhouLiu/BILIBILI-HELPER-PRE] 运行后的界面中文是乱码,请问怎么解决? (#62)





 
请在终端输入
 chcp 65001
 再运行jar包
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
