### ISSUE TITLE
腾讯云函数

### ISSUE THREAD

**Issue by tuoxiao** [JunzhouLiu/BILIBILI-HELPER-PRE#9]
腾讯云函数部署方式已经挂了，请问能不能抽时间补充？

**Comment by JunzhouLiu** [comment]
没有挂，参考本仓库docs/scf文档。

**Comment by JunzhouLiu** [comment]
https://github.com/JunzhouLiu/BILIBILI-HELPER-PRE/blob/main/docs/scf.md

**Comment by tuoxiao** [comment]
感谢！！
